stuff
TheProKoen/zeddy-server-public-configs pull request #11
Opened 2024-10-12 10:21 UTC by Whennya

update configs with incorrect format, add lyrics for mashup, fix new lucid dream config

2024-10-12 10:23 UTC, Whennya commented
ze_ffvii_malgo_reactor_css5 is missing all the ggeasy stages, ill add them at somepoint when i have free time + motivation to sit down for an hour and go through the billion songs malgo added

2024-11-01 05:57 UTC, notkoen requested changes

2024-11-01 05:57 UTC, notkoen commented on lyrics/ze_ffvii_malgo_reactor_css5.lua
Use tabs for all lua files.

2024-11-01 05:57 UTC, notkoen commented on lyrics/ze_sandstorm_css_v1_5x3.lua
I prefer not having emtpy lines at the bottom of files.

2024-11-01 05:57 UTC, notkoen commented on lyrics/zs_obj_megamashup_arena_ze_hns_ttt_gm_zi2.lua
Nitpick: I want consistency between timings. I want lyrics down to one decimal place.

2024-11-01 05:57 UTC, notkoen commented on musicname/ze_ffvii_malgo_reactor_css5.cfg
> +    "rmzs_second.mp3"                           "MUZZ - Play (ft. UK:ID), MUZZ - Back To You"
`Back to You` was made by both Muzzy and Voicians.
```suggestion
    "rmzs_second.mp3"                           "MUZZ - Play (ft. UK:ID), Muzzy & Voicians - Back To You"
```

2024-11-01 05:57 UTC, notkoen commented on musicname/ze_ffvii_malgo_reactor_css5.cfg
I am unsure whether if it should be Muzzy or MUZZ. I would say go off of what is on YouTube.

2024-11-01 05:57 UTC, notkoen commented on musicname/ze_serpentis_temple_v2a.cfg
Did you delete the brackets by accident?

2024-11-01 05:57 UTC, notkoen commented on musicname/ze_shroomforest_v4_5.cfg
>      "pokefloats.mp3"                                                            "Super Smash Bros. Melee - Poké Floats"
```suggestion
    "opening - donkey kong.mp3"                                                 "Super Smash Bros. Wii U OST - Opening (Donkey Kong)"
    "pokefloats.mp3"                                                            "Super Smash Bros. Melee OST - Poké Floats"
```

2024-11-01 05:57 UTC, notkoen commented on musicname/ze_shroomforest_v4_5.cfg
> +    "the fellowship of the ring soundtrack-02-concerning hobbits.mp3"           "The Fellowship of the Ring - Concerning Hobbits"
Add LOTR to the name?
```suggestion
    "the fellowship of the ring soundtrack-02-concerning hobbits.mp3"           "LOTR: The Fellowship of the Ring OST - Concerning Hobbits"
```

2024-11-01 05:57 UTC, notkoen commented on musicname/ze_v0u0v_b2.cfg
Remove whitespace at end of file, and use spaces for consistent formatting.

2024-11-01 05:57 UTC, notkoen commented on musicname/zs_obj_megamashup_arena_ze_hns_ttt_gm_zi2.cfg
Is there a reason why `w3_rocksteady.mp3` is commented out?

2024-11-01 05:57 UTC, notkoen reviewed
> ze_ffvii_malgo_reactor_css5 is missing all the ggeasy songs, ill add them at somepoint when i have free time + motivation to sit down for an hour and go through the billion songs malgo added 

I hope you can add the songs in when you are free. Otherwise, I appreciate the work.

2024-11-01 08:07 UTC, Whennya commented on musicname/zs_obj_megamashup_arena_ze_hns_ttt_gm_zi2.cfg
https://discord.com/channels/353474260112769026/988880052030693446/1291848041095233757
song file was replaced by iszaar and just updated config as he said

2024-11-01 08:14 UTC, Whennya commented on musicname/ze_ffvii_malgo_reactor_css5.cfg
MUZZ is the name of the artist's channel on youtube music (?) while Muzzy is what is reposted by Monstercat and other channels, so I'm not sure which, they're the same person but i think it depends on where it was uploaded?

2024-11-01 08:17 UTC, Whennya commented on lyrics/zs_obj_megamashup_arena_ze_hns_ttt_gm_zi2.lua
the config was stolen from lms since they seemed to be the same file when i checked, but i changed both

2024-11-01 08:35 UTC, notkoen commented on musicname/ze_ffvii_malgo_reactor_css5.cfg
I want to keep consistency across all songs (and configs as well). I would personally stick to Muzzy but I will let you make the call here.

2024-11-01 16:33 UTC, notkoen reviewed
LGTM

2024-11-01 16:33 UTC, notkoen approved these changes

2024-11-01 16:33 UTC, merged