i hecking love surf!
TheProKoen/zeddy-server-public-configs pull request #6
Opened 2024-09-16 21:04 UTC by Whennya

Add configs for 18 surf maps:
- ze_re_surf_skyline_ep_rf3
- ze_surf_bona_s2
- ze_surf_charge_v2_f2
- ze_surf_cherry_blossom_v4_1
- ze_surf_danger
- ze_surf_dark_fantasy_v1
- ze_surf_daybreak_v1_1
- ze_surf_facility_v2_3
- ze_surf_gypt_v1_3s
- ze_surf_hp_v1_2_s2
- ze_surf_last_point_v1_5
- ze_surf_luna_v3_f4
- ze_surf_outside_s3
- ze_surf_saltfish_css2
- ze_surf_shonyudo_v5_2s
- ze_surf_sky_v1_3
- ze_surf_sphinx_stronghold_a5
- ze_surf_virtus_s_ep_f4

2024-09-16 21:36 UTC, notkoen commented on musicname/ze_surf_bona_s2.cfg
> +    "nothings gonna stop us tonight.mp3"                    "ANNALISE - NOTHING GONNA STOP US TONIGHT"
```suggestion
    "kiss.mp3"                                              "Bamboo Bimbo - Kiss"
    "nothings gonna stop us tonight.mp3"                    "Annalise - Nothing's Gonna Stop Us Tonight"
```

2024-09-16 21:36 UTC, notkoen commented on musicname/ze_surf_dark_fantasy_v1.cfg
> +    "muzzy - new age (feat. celldweller) [monstercat release].mp3"              "Muzzy - New Age (feat. Celldweller)"
```suggestion
    "muzzy - new age (feat. celldweller) [monstercat release].mp3"              "Muzzy - New Age (ft. Celldweller)"
```

2024-09-16 21:36 UTC, notkoen commented on musicname/ze_surf_dark_fantasy_v1.cfg
> +    "droeloe feat. nevve - backbone.mp3"                                        "DROELOE - BACKBONE (feat. Nevve)"
```suggestion
    "droeloe feat. nevve - backbone.mp3"                                        "DROELOE - BACKBONE (ft. Nevve)"
```

2024-09-16 21:36 UTC, notkoen commented on musicname/ze_surf_dark_fantasy_v1.cfg
> +    "varien feat. laura brehm - valkyrie.mp3"                                   "Varien - Valkyrie (feat. Laura Brehm)"
```suggestion
    "telykast feat. jordy - somebody else (kc audio remix).mp3"                 "TELYKast - Somebody Else (ft. JORDY, KC Audio Remix)"
    "triple m - 2gether.mp3"                                                    "Triple M - 2GETHER"
    "varien feat. laura brehm - valkyrie.mp3"                                   "Varien - Valkyrie (ft. Laura Brehm)"
```

2024-09-16 21:36 UTC, notkoen commented on musicname/ze_surf_dark_fantasy_v1.cfg
> +    "alan walker - different world.mp3"                                         "Alan Walker - Different World feat. Sofia Carson, K-391 & CORSAK"
```suggestion
    "alan walker - different world.mp3"                                         "Alan Walker - Different World (ft. Sofia Carson, K-391 & CORSAK)"
```

2024-09-16 21:36 UTC, notkoen commented on musicname/ze_surf_dark_fantasy_v1.cfg
> +    "end of silence - when will you save me (feat. julie elven).mp3"            "End Of Silence - When Will You Save Me (feat. Julie Elven)"
```suggestion
    "end of silence - when will you save me (feat. julie elven).mp3"            "End Of Silence - When Will You Save Me (ft. Julie Elven)"
```

2024-09-16 21:36 UTC, notkoen commented on musicname/ze_surf_dark_fantasy_v1.cfg
> +    "efisio cross - if you fall i will carry you.mp3"                           "Efisio Cross - If you fall i will carry you"
```suggestion
    "efisio cross - if you fall i will carry you.mp3"                           "Efisio Cross - If You Fall I Will Carry You"
```

2024-09-16 21:36 UTC, notkoen commented on musicname/ze_surf_last_point_v1_5.cfg
For the different music from Black Mesa, you could change it to `Joel Nielsen - <music name> (Black Mesa OST)`

2024-09-16 21:43 UTC, Whennya reviewed
update configs

2024-09-17 04:37 UTC, notkoen requested changes
Remaining issues I spotted. Hopefully I didn't mist anything.

2024-09-17 04:37 UTC, notkoen commented on musicname/ze_surf_dark_fantasy_v1.cfg
> +    "alan walker - different world.mp3"                                         "Alan Walker - Different World ft. (Sofia Carson, K-391 & CORSAK)"
```suggestion
    "alan walker - different world.mp3"                                         "Alan Walker - Different World (ft. Sofia Carson, K-391 & CORSAK)"
```

2024-09-17 04:37 UTC, notkoen commented on musicname/ze_surf_dark_fantasy_v1.cfg
> +    "telykast feat. jordy - somebody else (kc audio remix).mp3"                 "TELYKast - Somebody Else (feat. JORDY, KC Audio Remix)"
```suggestion
    "telykast feat. jordy - somebody else (kc audio remix).mp3"                 "TELYKast - Somebody Else (ft. JORDY, KC Audio Remix)"
```

2024-09-17 15:31 UTC, merged